version: '3.8'

services:

  jesse:
    image: salehmir/jesse:latest
    depends_on:
      - postgres
      - redis
    env_file:
      .env
    ports:
      - 8888:8888
      - 8000:8000
    volumes:
      - ./jesseData:/home
    tty: true


  redis:
    image: redis:6.2.5-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    hostname: redis
    ports:
      - ${REDIS_PORT}:6379

  postgres:
    image: postgres:12-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./dbData:/var/lib/postgresql/data