version: '3.8'

services:

  jesse:
    image: salehmir/jesse:python38
    volumes:
      - ./jesseData:/home
    depends_on:
      - db
      - jesse-trades-info
    environment:
      POSTGRES_HOST: "db"
    ports:
      - 8888:8888

  jesse-trades-info:
    image: jessetradesinfo/jesse-trades-info:v0.1.0
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: jesse_db
      DB_USER: jesse_user
      DB_PASSWORD: password
      DB_PORT: 5432
    ports:
      - 3000:3000

  db:
    build:
      context: ./postgres
    volumes:
      - ./dbData:/var/lib/postgresql/data
    ports:
      - 5432:5432
