version: '3.8'

services:

  jesse:
    image: salehmir/jesse:latest
    depends_on:
      - postgres
      - redis
    ports:
      - 8888:8888
      - 8000:8000
    volumes:
      - ./jesseData:/home
    tty: true


  redis:
    image: redis:6.2.5-alpine
    # uncomment this if you want to protect redis with a password.
    # command: redis-server --requirepass mypassword
    hostname: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:14-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: jesse_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jesse_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - 5432:5432
    volumes:
      - ./dbData:/var/lib/postgresql/data
